// Code generated by go-swagger; DO NOT EDIT.

package circuits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CircuitsProvidersReadReader is a Reader for the CircuitsProvidersRead structure.
type CircuitsProvidersReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CircuitsProvidersReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCircuitsProvidersReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCircuitsProvidersReadOK creates a CircuitsProvidersReadOK with default headers values
func NewCircuitsProvidersReadOK() *CircuitsProvidersReadOK {
	return &CircuitsProvidersReadOK{}
}

/*CircuitsProvidersReadOK handles this case with default header values.

CircuitsProvidersReadOK circuits providers read o k
*/
type CircuitsProvidersReadOK struct {
}

func (o *CircuitsProvidersReadOK) Error() string {
	return fmt.Sprintf("[GET /api/circuits/providers/{id}/][%d] circuitsProvidersReadOK ", 200)
}

func (o *CircuitsProvidersReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
