// Code generated by go-swagger; DO NOT EDIT.

package circuits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCircuitsCircuitsReadParams creates a new CircuitsCircuitsReadParams object
// with the default values initialized.
func NewCircuitsCircuitsReadParams() *CircuitsCircuitsReadParams {
	var ()
	return &CircuitsCircuitsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCircuitsCircuitsReadParamsWithTimeout creates a new CircuitsCircuitsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCircuitsCircuitsReadParamsWithTimeout(timeout time.Duration) *CircuitsCircuitsReadParams {
	var ()
	return &CircuitsCircuitsReadParams{

		timeout: timeout,
	}
}

// NewCircuitsCircuitsReadParamsWithContext creates a new CircuitsCircuitsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewCircuitsCircuitsReadParamsWithContext(ctx context.Context) *CircuitsCircuitsReadParams {
	var ()
	return &CircuitsCircuitsReadParams{

		Context: ctx,
	}
}

// NewCircuitsCircuitsReadParamsWithHTTPClient creates a new CircuitsCircuitsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCircuitsCircuitsReadParamsWithHTTPClient(client *http.Client) *CircuitsCircuitsReadParams {
	var ()
	return &CircuitsCircuitsReadParams{
		HTTPClient: client,
	}
}

/*CircuitsCircuitsReadParams contains all the parameters to send to the API endpoint
for the circuits circuits read operation typically these are written to a http.Request
*/
type CircuitsCircuitsReadParams struct {

	/*Cid*/
	Cid *string
	/*CommitRate*/
	CommitRate *float64
	/*ID
	  A unique integer value identifying this circuit.

	*/
	ID int64
	/*IDIn
	  Multiple values may be separated by commas.

	*/
	IDIn *float64
	/*InstallDate*/
	InstallDate *string
	/*Provider*/
	Provider *string
	/*ProviderID*/
	ProviderID *string
	/*Q*/
	Q *string
	/*Site*/
	Site *string
	/*SiteID*/
	SiteID *string
	/*Tenant*/
	Tenant *string
	/*TenantID*/
	TenantID *string
	/*Type*/
	Type *string
	/*TypeID*/
	TypeID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithTimeout(timeout time.Duration) *CircuitsCircuitsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithContext(ctx context.Context) *CircuitsCircuitsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithHTTPClient(client *http.Client) *CircuitsCircuitsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCid adds the cid to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithCid(cid *string) *CircuitsCircuitsReadParams {
	o.SetCid(cid)
	return o
}

// SetCid adds the cid to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetCid(cid *string) {
	o.Cid = cid
}

// WithCommitRate adds the commitRate to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithCommitRate(commitRate *float64) *CircuitsCircuitsReadParams {
	o.SetCommitRate(commitRate)
	return o
}

// SetCommitRate adds the commitRate to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetCommitRate(commitRate *float64) {
	o.CommitRate = commitRate
}

// WithID adds the id to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithID(id int64) *CircuitsCircuitsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetID(id int64) {
	o.ID = id
}

// WithIDIn adds the iDIn to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithIDIn(iDIn *float64) *CircuitsCircuitsReadParams {
	o.SetIDIn(iDIn)
	return o
}

// SetIDIn adds the idIn to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetIDIn(iDIn *float64) {
	o.IDIn = iDIn
}

// WithInstallDate adds the installDate to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithInstallDate(installDate *string) *CircuitsCircuitsReadParams {
	o.SetInstallDate(installDate)
	return o
}

// SetInstallDate adds the installDate to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetInstallDate(installDate *string) {
	o.InstallDate = installDate
}

// WithProvider adds the provider to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithProvider(provider *string) *CircuitsCircuitsReadParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetProvider(provider *string) {
	o.Provider = provider
}

// WithProviderID adds the providerID to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithProviderID(providerID *string) *CircuitsCircuitsReadParams {
	o.SetProviderID(providerID)
	return o
}

// SetProviderID adds the providerId to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetProviderID(providerID *string) {
	o.ProviderID = providerID
}

// WithQ adds the q to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithQ(q *string) *CircuitsCircuitsReadParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetQ(q *string) {
	o.Q = q
}

// WithSite adds the site to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithSite(site *string) *CircuitsCircuitsReadParams {
	o.SetSite(site)
	return o
}

// SetSite adds the site to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetSite(site *string) {
	o.Site = site
}

// WithSiteID adds the siteID to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithSiteID(siteID *string) *CircuitsCircuitsReadParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetSiteID(siteID *string) {
	o.SiteID = siteID
}

// WithTenant adds the tenant to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithTenant(tenant *string) *CircuitsCircuitsReadParams {
	o.SetTenant(tenant)
	return o
}

// SetTenant adds the tenant to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetTenant(tenant *string) {
	o.Tenant = tenant
}

// WithTenantID adds the tenantID to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithTenantID(tenantID *string) *CircuitsCircuitsReadParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetTenantID(tenantID *string) {
	o.TenantID = tenantID
}

// WithType adds the typeVar to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithType(typeVar *string) *CircuitsCircuitsReadParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WithTypeID adds the typeID to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) WithTypeID(typeID *string) *CircuitsCircuitsReadParams {
	o.SetTypeID(typeID)
	return o
}

// SetTypeID adds the typeId to the circuits circuits read params
func (o *CircuitsCircuitsReadParams) SetTypeID(typeID *string) {
	o.TypeID = typeID
}

// WriteToRequest writes these params to a swagger request
func (o *CircuitsCircuitsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cid != nil {

		// query param cid
		var qrCid string
		if o.Cid != nil {
			qrCid = *o.Cid
		}
		qCid := qrCid
		if qCid != "" {
			if err := r.SetQueryParam("cid", qCid); err != nil {
				return err
			}
		}

	}

	if o.CommitRate != nil {

		// query param commit_rate
		var qrCommitRate float64
		if o.CommitRate != nil {
			qrCommitRate = *o.CommitRate
		}
		qCommitRate := swag.FormatFloat64(qrCommitRate)
		if qCommitRate != "" {
			if err := r.SetQueryParam("commit_rate", qCommitRate); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.IDIn != nil {

		// query param id__in
		var qrIDIn float64
		if o.IDIn != nil {
			qrIDIn = *o.IDIn
		}
		qIDIn := swag.FormatFloat64(qrIDIn)
		if qIDIn != "" {
			if err := r.SetQueryParam("id__in", qIDIn); err != nil {
				return err
			}
		}

	}

	if o.InstallDate != nil {

		// query param install_date
		var qrInstallDate string
		if o.InstallDate != nil {
			qrInstallDate = *o.InstallDate
		}
		qInstallDate := qrInstallDate
		if qInstallDate != "" {
			if err := r.SetQueryParam("install_date", qInstallDate); err != nil {
				return err
			}
		}

	}

	if o.Provider != nil {

		// query param provider
		var qrProvider string
		if o.Provider != nil {
			qrProvider = *o.Provider
		}
		qProvider := qrProvider
		if qProvider != "" {
			if err := r.SetQueryParam("provider", qProvider); err != nil {
				return err
			}
		}

	}

	if o.ProviderID != nil {

		// query param provider_id
		var qrProviderID string
		if o.ProviderID != nil {
			qrProviderID = *o.ProviderID
		}
		qProviderID := qrProviderID
		if qProviderID != "" {
			if err := r.SetQueryParam("provider_id", qProviderID); err != nil {
				return err
			}
		}

	}

	if o.Q != nil {

		// query param q
		var qrQ string
		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {
			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}

	}

	if o.Site != nil {

		// query param site
		var qrSite string
		if o.Site != nil {
			qrSite = *o.Site
		}
		qSite := qrSite
		if qSite != "" {
			if err := r.SetQueryParam("site", qSite); err != nil {
				return err
			}
		}

	}

	if o.SiteID != nil {

		// query param site_id
		var qrSiteID string
		if o.SiteID != nil {
			qrSiteID = *o.SiteID
		}
		qSiteID := qrSiteID
		if qSiteID != "" {
			if err := r.SetQueryParam("site_id", qSiteID); err != nil {
				return err
			}
		}

	}

	if o.Tenant != nil {

		// query param tenant
		var qrTenant string
		if o.Tenant != nil {
			qrTenant = *o.Tenant
		}
		qTenant := qrTenant
		if qTenant != "" {
			if err := r.SetQueryParam("tenant", qTenant); err != nil {
				return err
			}
		}

	}

	if o.TenantID != nil {

		// query param tenant_id
		var qrTenantID string
		if o.TenantID != nil {
			qrTenantID = *o.TenantID
		}
		qTenantID := qrTenantID
		if qTenantID != "" {
			if err := r.SetQueryParam("tenant_id", qTenantID); err != nil {
				return err
			}
		}

	}

	if o.Type != nil {

		// query param type
		var qrType string
		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {
			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}

	}

	if o.TypeID != nil {

		// query param type_id
		var qrTypeID string
		if o.TypeID != nil {
			qrTypeID = *o.TypeID
		}
		qTypeID := qrTypeID
		if qTypeID != "" {
			if err := r.SetQueryParam("type_id", qTypeID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
