// Code generated by go-swagger; DO NOT EDIT.

package circuits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CircuitsCircuitTypesListReader is a Reader for the CircuitsCircuitTypesList structure.
type CircuitsCircuitTypesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CircuitsCircuitTypesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCircuitsCircuitTypesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCircuitsCircuitTypesListOK creates a CircuitsCircuitTypesListOK with default headers values
func NewCircuitsCircuitTypesListOK() *CircuitsCircuitTypesListOK {
	return &CircuitsCircuitTypesListOK{}
}

/*CircuitsCircuitTypesListOK handles this case with default header values.

CircuitsCircuitTypesListOK circuits circuit types list o k
*/
type CircuitsCircuitTypesListOK struct {
}

func (o *CircuitsCircuitTypesListOK) Error() string {
	return fmt.Sprintf("[GET /api/circuits/circuit-types/][%d] circuitsCircuitTypesListOK ", 200)
}

func (o *CircuitsCircuitTypesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
