// Code generated by go-swagger; DO NOT EDIT.

package tenancy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// TenancyTenantGroupsReadReader is a Reader for the TenancyTenantGroupsRead structure.
type TenancyTenantGroupsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TenancyTenantGroupsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTenancyTenantGroupsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTenancyTenantGroupsReadOK creates a TenancyTenantGroupsReadOK with default headers values
func NewTenancyTenantGroupsReadOK() *TenancyTenantGroupsReadOK {
	return &TenancyTenantGroupsReadOK{}
}

/*TenancyTenantGroupsReadOK handles this case with default header values.

TenancyTenantGroupsReadOK tenancy tenant groups read o k
*/
type TenancyTenantGroupsReadOK struct {
}

func (o *TenancyTenantGroupsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/tenancy/tenant-groups/{id}/][%d] tenancyTenantGroupsReadOK ", 200)
}

func (o *TenancyTenantGroupsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
