// Code generated by go-swagger; DO NOT EDIT.

package tenancy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// TenancyTenantGroupsListReader is a Reader for the TenancyTenantGroupsList structure.
type TenancyTenantGroupsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TenancyTenantGroupsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTenancyTenantGroupsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTenancyTenantGroupsListOK creates a TenancyTenantGroupsListOK with default headers values
func NewTenancyTenantGroupsListOK() *TenancyTenantGroupsListOK {
	return &TenancyTenantGroupsListOK{}
}

/*TenancyTenantGroupsListOK handles this case with default header values.

TenancyTenantGroupsListOK tenancy tenant groups list o k
*/
type TenancyTenantGroupsListOK struct {
}

func (o *TenancyTenantGroupsListOK) Error() string {
	return fmt.Sprintf("[GET /api/tenancy/tenant-groups/][%d] tenancyTenantGroupsListOK ", 200)
}

func (o *TenancyTenantGroupsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
