// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIPAMRirsReadParams creates a new IPAMRirsReadParams object
// with the default values initialized.
func NewIPAMRirsReadParams() *IPAMRirsReadParams {
	var ()
	return &IPAMRirsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIPAMRirsReadParamsWithTimeout creates a new IPAMRirsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIPAMRirsReadParamsWithTimeout(timeout time.Duration) *IPAMRirsReadParams {
	var ()
	return &IPAMRirsReadParams{

		timeout: timeout,
	}
}

// NewIPAMRirsReadParamsWithContext creates a new IPAMRirsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewIPAMRirsReadParamsWithContext(ctx context.Context) *IPAMRirsReadParams {
	var ()
	return &IPAMRirsReadParams{

		Context: ctx,
	}
}

// NewIPAMRirsReadParamsWithHTTPClient creates a new IPAMRirsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIPAMRirsReadParamsWithHTTPClient(client *http.Client) *IPAMRirsReadParams {
	var ()
	return &IPAMRirsReadParams{
		HTTPClient: client,
	}
}

/*IPAMRirsReadParams contains all the parameters to send to the API endpoint
for the ipam rirs read operation typically these are written to a http.Request
*/
type IPAMRirsReadParams struct {

	/*ID
	  A unique integer value identifying this RIR.

	*/
	ID int64
	/*IDIn
	  Multiple values may be separated by commas.

	*/
	IDIn *float64
	/*IsPrivate*/
	IsPrivate *string
	/*Name*/
	Name *string
	/*Slug*/
	Slug *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ipam rirs read params
func (o *IPAMRirsReadParams) WithTimeout(timeout time.Duration) *IPAMRirsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ipam rirs read params
func (o *IPAMRirsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ipam rirs read params
func (o *IPAMRirsReadParams) WithContext(ctx context.Context) *IPAMRirsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ipam rirs read params
func (o *IPAMRirsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ipam rirs read params
func (o *IPAMRirsReadParams) WithHTTPClient(client *http.Client) *IPAMRirsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ipam rirs read params
func (o *IPAMRirsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the ipam rirs read params
func (o *IPAMRirsReadParams) WithID(id int64) *IPAMRirsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ipam rirs read params
func (o *IPAMRirsReadParams) SetID(id int64) {
	o.ID = id
}

// WithIDIn adds the iDIn to the ipam rirs read params
func (o *IPAMRirsReadParams) WithIDIn(iDIn *float64) *IPAMRirsReadParams {
	o.SetIDIn(iDIn)
	return o
}

// SetIDIn adds the idIn to the ipam rirs read params
func (o *IPAMRirsReadParams) SetIDIn(iDIn *float64) {
	o.IDIn = iDIn
}

// WithIsPrivate adds the isPrivate to the ipam rirs read params
func (o *IPAMRirsReadParams) WithIsPrivate(isPrivate *string) *IPAMRirsReadParams {
	o.SetIsPrivate(isPrivate)
	return o
}

// SetIsPrivate adds the isPrivate to the ipam rirs read params
func (o *IPAMRirsReadParams) SetIsPrivate(isPrivate *string) {
	o.IsPrivate = isPrivate
}

// WithName adds the name to the ipam rirs read params
func (o *IPAMRirsReadParams) WithName(name *string) *IPAMRirsReadParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the ipam rirs read params
func (o *IPAMRirsReadParams) SetName(name *string) {
	o.Name = name
}

// WithSlug adds the slug to the ipam rirs read params
func (o *IPAMRirsReadParams) WithSlug(slug *string) *IPAMRirsReadParams {
	o.SetSlug(slug)
	return o
}

// SetSlug adds the slug to the ipam rirs read params
func (o *IPAMRirsReadParams) SetSlug(slug *string) {
	o.Slug = slug
}

// WriteToRequest writes these params to a swagger request
func (o *IPAMRirsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.IDIn != nil {

		// query param id__in
		var qrIDIn float64
		if o.IDIn != nil {
			qrIDIn = *o.IDIn
		}
		qIDIn := swag.FormatFloat64(qrIDIn)
		if qIDIn != "" {
			if err := r.SetQueryParam("id__in", qIDIn); err != nil {
				return err
			}
		}

	}

	if o.IsPrivate != nil {

		// query param is_private
		var qrIsPrivate string
		if o.IsPrivate != nil {
			qrIsPrivate = *o.IsPrivate
		}
		qIsPrivate := qrIsPrivate
		if qIsPrivate != "" {
			if err := r.SetQueryParam("is_private", qIsPrivate); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Slug != nil {

		// query param slug
		var qrSlug string
		if o.Slug != nil {
			qrSlug = *o.Slug
		}
		qSlug := qrSlug
		if qSlug != "" {
			if err := r.SetQueryParam("slug", qSlug); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
