// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIPAMIPAddressesReadParams creates a new IPAMIPAddressesReadParams object
// with the default values initialized.
func NewIPAMIPAddressesReadParams() *IPAMIPAddressesReadParams {
	var ()
	return &IPAMIPAddressesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIPAMIPAddressesReadParamsWithTimeout creates a new IPAMIPAddressesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIPAMIPAddressesReadParamsWithTimeout(timeout time.Duration) *IPAMIPAddressesReadParams {
	var ()
	return &IPAMIPAddressesReadParams{

		timeout: timeout,
	}
}

// NewIPAMIPAddressesReadParamsWithContext creates a new IPAMIPAddressesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewIPAMIPAddressesReadParamsWithContext(ctx context.Context) *IPAMIPAddressesReadParams {
	var ()
	return &IPAMIPAddressesReadParams{

		Context: ctx,
	}
}

// NewIPAMIPAddressesReadParamsWithHTTPClient creates a new IPAMIPAddressesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIPAMIPAddressesReadParamsWithHTTPClient(client *http.Client) *IPAMIPAddressesReadParams {
	var ()
	return &IPAMIPAddressesReadParams{
		HTTPClient: client,
	}
}

/*IPAMIPAddressesReadParams contains all the parameters to send to the API endpoint
for the ipam ip addresses read operation typically these are written to a http.Request
*/
type IPAMIPAddressesReadParams struct {

	/*Device*/
	Device *string
	/*DeviceID*/
	DeviceID *string
	/*Family*/
	Family *string
	/*ID
	  A unique integer value identifying this IP address.

	*/
	ID int64
	/*IDIn
	  Multiple values may be separated by commas.

	*/
	IDIn *float64
	/*InterfaceID*/
	InterfaceID *string
	/*MaskLength*/
	MaskLength *float64
	/*Parent*/
	Parent *string
	/*Q*/
	Q *string
	/*Role*/
	Role *string
	/*Status*/
	Status *string
	/*Tenant*/
	Tenant *string
	/*TenantID*/
	TenantID *string
	/*VirtualMachine*/
	VirtualMachine *string
	/*VirtualMachineID*/
	VirtualMachineID *string
	/*Vrf*/
	Vrf *string
	/*VrfID*/
	VrfID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithTimeout(timeout time.Duration) *IPAMIPAddressesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithContext(ctx context.Context) *IPAMIPAddressesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithHTTPClient(client *http.Client) *IPAMIPAddressesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevice adds the device to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithDevice(device *string) *IPAMIPAddressesReadParams {
	o.SetDevice(device)
	return o
}

// SetDevice adds the device to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetDevice(device *string) {
	o.Device = device
}

// WithDeviceID adds the deviceID to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithDeviceID(deviceID *string) *IPAMIPAddressesReadParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetDeviceID(deviceID *string) {
	o.DeviceID = deviceID
}

// WithFamily adds the family to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithFamily(family *string) *IPAMIPAddressesReadParams {
	o.SetFamily(family)
	return o
}

// SetFamily adds the family to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetFamily(family *string) {
	o.Family = family
}

// WithID adds the id to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithID(id int64) *IPAMIPAddressesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetID(id int64) {
	o.ID = id
}

// WithIDIn adds the iDIn to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithIDIn(iDIn *float64) *IPAMIPAddressesReadParams {
	o.SetIDIn(iDIn)
	return o
}

// SetIDIn adds the idIn to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetIDIn(iDIn *float64) {
	o.IDIn = iDIn
}

// WithInterfaceID adds the interfaceID to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithInterfaceID(interfaceID *string) *IPAMIPAddressesReadParams {
	o.SetInterfaceID(interfaceID)
	return o
}

// SetInterfaceID adds the interfaceId to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetInterfaceID(interfaceID *string) {
	o.InterfaceID = interfaceID
}

// WithMaskLength adds the maskLength to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithMaskLength(maskLength *float64) *IPAMIPAddressesReadParams {
	o.SetMaskLength(maskLength)
	return o
}

// SetMaskLength adds the maskLength to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetMaskLength(maskLength *float64) {
	o.MaskLength = maskLength
}

// WithParent adds the parent to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithParent(parent *string) *IPAMIPAddressesReadParams {
	o.SetParent(parent)
	return o
}

// SetParent adds the parent to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetParent(parent *string) {
	o.Parent = parent
}

// WithQ adds the q to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithQ(q *string) *IPAMIPAddressesReadParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetQ(q *string) {
	o.Q = q
}

// WithRole adds the role to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithRole(role *string) *IPAMIPAddressesReadParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetRole(role *string) {
	o.Role = role
}

// WithStatus adds the status to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithStatus(status *string) *IPAMIPAddressesReadParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetStatus(status *string) {
	o.Status = status
}

// WithTenant adds the tenant to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithTenant(tenant *string) *IPAMIPAddressesReadParams {
	o.SetTenant(tenant)
	return o
}

// SetTenant adds the tenant to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetTenant(tenant *string) {
	o.Tenant = tenant
}

// WithTenantID adds the tenantID to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithTenantID(tenantID *string) *IPAMIPAddressesReadParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetTenantID(tenantID *string) {
	o.TenantID = tenantID
}

// WithVirtualMachine adds the virtualMachine to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithVirtualMachine(virtualMachine *string) *IPAMIPAddressesReadParams {
	o.SetVirtualMachine(virtualMachine)
	return o
}

// SetVirtualMachine adds the virtualMachine to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetVirtualMachine(virtualMachine *string) {
	o.VirtualMachine = virtualMachine
}

// WithVirtualMachineID adds the virtualMachineID to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithVirtualMachineID(virtualMachineID *string) *IPAMIPAddressesReadParams {
	o.SetVirtualMachineID(virtualMachineID)
	return o
}

// SetVirtualMachineID adds the virtualMachineId to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetVirtualMachineID(virtualMachineID *string) {
	o.VirtualMachineID = virtualMachineID
}

// WithVrf adds the vrf to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithVrf(vrf *string) *IPAMIPAddressesReadParams {
	o.SetVrf(vrf)
	return o
}

// SetVrf adds the vrf to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetVrf(vrf *string) {
	o.Vrf = vrf
}

// WithVrfID adds the vrfID to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) WithVrfID(vrfID *string) *IPAMIPAddressesReadParams {
	o.SetVrfID(vrfID)
	return o
}

// SetVrfID adds the vrfId to the ipam ip addresses read params
func (o *IPAMIPAddressesReadParams) SetVrfID(vrfID *string) {
	o.VrfID = vrfID
}

// WriteToRequest writes these params to a swagger request
func (o *IPAMIPAddressesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Device != nil {

		// query param device
		var qrDevice string
		if o.Device != nil {
			qrDevice = *o.Device
		}
		qDevice := qrDevice
		if qDevice != "" {
			if err := r.SetQueryParam("device", qDevice); err != nil {
				return err
			}
		}

	}

	if o.DeviceID != nil {

		// query param device_id
		var qrDeviceID string
		if o.DeviceID != nil {
			qrDeviceID = *o.DeviceID
		}
		qDeviceID := qrDeviceID
		if qDeviceID != "" {
			if err := r.SetQueryParam("device_id", qDeviceID); err != nil {
				return err
			}
		}

	}

	if o.Family != nil {

		// query param family
		var qrFamily string
		if o.Family != nil {
			qrFamily = *o.Family
		}
		qFamily := qrFamily
		if qFamily != "" {
			if err := r.SetQueryParam("family", qFamily); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.IDIn != nil {

		// query param id__in
		var qrIDIn float64
		if o.IDIn != nil {
			qrIDIn = *o.IDIn
		}
		qIDIn := swag.FormatFloat64(qrIDIn)
		if qIDIn != "" {
			if err := r.SetQueryParam("id__in", qIDIn); err != nil {
				return err
			}
		}

	}

	if o.InterfaceID != nil {

		// query param interface_id
		var qrInterfaceID string
		if o.InterfaceID != nil {
			qrInterfaceID = *o.InterfaceID
		}
		qInterfaceID := qrInterfaceID
		if qInterfaceID != "" {
			if err := r.SetQueryParam("interface_id", qInterfaceID); err != nil {
				return err
			}
		}

	}

	if o.MaskLength != nil {

		// query param mask_length
		var qrMaskLength float64
		if o.MaskLength != nil {
			qrMaskLength = *o.MaskLength
		}
		qMaskLength := swag.FormatFloat64(qrMaskLength)
		if qMaskLength != "" {
			if err := r.SetQueryParam("mask_length", qMaskLength); err != nil {
				return err
			}
		}

	}

	if o.Parent != nil {

		// query param parent
		var qrParent string
		if o.Parent != nil {
			qrParent = *o.Parent
		}
		qParent := qrParent
		if qParent != "" {
			if err := r.SetQueryParam("parent", qParent); err != nil {
				return err
			}
		}

	}

	if o.Q != nil {

		// query param q
		var qrQ string
		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {
			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}

	}

	if o.Role != nil {

		// query param role
		var qrRole string
		if o.Role != nil {
			qrRole = *o.Role
		}
		qRole := qrRole
		if qRole != "" {
			if err := r.SetQueryParam("role", qRole); err != nil {
				return err
			}
		}

	}

	if o.Status != nil {

		// query param status
		var qrStatus string
		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {
			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}

	}

	if o.Tenant != nil {

		// query param tenant
		var qrTenant string
		if o.Tenant != nil {
			qrTenant = *o.Tenant
		}
		qTenant := qrTenant
		if qTenant != "" {
			if err := r.SetQueryParam("tenant", qTenant); err != nil {
				return err
			}
		}

	}

	if o.TenantID != nil {

		// query param tenant_id
		var qrTenantID string
		if o.TenantID != nil {
			qrTenantID = *o.TenantID
		}
		qTenantID := qrTenantID
		if qTenantID != "" {
			if err := r.SetQueryParam("tenant_id", qTenantID); err != nil {
				return err
			}
		}

	}

	if o.VirtualMachine != nil {

		// query param virtual_machine
		var qrVirtualMachine string
		if o.VirtualMachine != nil {
			qrVirtualMachine = *o.VirtualMachine
		}
		qVirtualMachine := qrVirtualMachine
		if qVirtualMachine != "" {
			if err := r.SetQueryParam("virtual_machine", qVirtualMachine); err != nil {
				return err
			}
		}

	}

	if o.VirtualMachineID != nil {

		// query param virtual_machine_id
		var qrVirtualMachineID string
		if o.VirtualMachineID != nil {
			qrVirtualMachineID = *o.VirtualMachineID
		}
		qVirtualMachineID := qrVirtualMachineID
		if qVirtualMachineID != "" {
			if err := r.SetQueryParam("virtual_machine_id", qVirtualMachineID); err != nil {
				return err
			}
		}

	}

	if o.Vrf != nil {

		// query param vrf
		var qrVrf string
		if o.Vrf != nil {
			qrVrf = *o.Vrf
		}
		qVrf := qrVrf
		if qVrf != "" {
			if err := r.SetQueryParam("vrf", qVrf); err != nil {
				return err
			}
		}

	}

	if o.VrfID != nil {

		// query param vrf_id
		var qrVrfID string
		if o.VrfID != nil {
			qrVrfID = *o.VrfID
		}
		qVrfID := qrVrfID
		if qVrfID != "" {
			if err := r.SetQueryParam("vrf_id", qVrfID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
