// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// IPAMVrfsListReader is a Reader for the IPAMVrfsList structure.
type IPAMVrfsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPAMVrfsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIPAMVrfsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIPAMVrfsListOK creates a IPAMVrfsListOK with default headers values
func NewIPAMVrfsListOK() *IPAMVrfsListOK {
	return &IPAMVrfsListOK{}
}

/*IPAMVrfsListOK handles this case with default header values.

IPAMVrfsListOK ipam vrfs list o k
*/
type IPAMVrfsListOK struct {
}

func (o *IPAMVrfsListOK) Error() string {
	return fmt.Sprintf("[GET /api/ipam/vrfs/][%d] ipamVrfsListOK ", 200)
}

func (o *IPAMVrfsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
