// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// IPAMRirsListReader is a Reader for the IPAMRirsList structure.
type IPAMRirsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPAMRirsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIPAMRirsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIPAMRirsListOK creates a IPAMRirsListOK with default headers values
func NewIPAMRirsListOK() *IPAMRirsListOK {
	return &IPAMRirsListOK{}
}

/*IPAMRirsListOK handles this case with default header values.

IPAMRirsListOK ipam rirs list o k
*/
type IPAMRirsListOK struct {
}

func (o *IPAMRirsListOK) Error() string {
	return fmt.Sprintf("[GET /api/ipam/rirs/][%d] ipamRirsListOK ", 200)
}

func (o *IPAMRirsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
