// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// IPAMAggregatesReadReader is a Reader for the IPAMAggregatesRead structure.
type IPAMAggregatesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPAMAggregatesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIPAMAggregatesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIPAMAggregatesReadOK creates a IPAMAggregatesReadOK with default headers values
func NewIPAMAggregatesReadOK() *IPAMAggregatesReadOK {
	return &IPAMAggregatesReadOK{}
}

/*IPAMAggregatesReadOK handles this case with default header values.

IPAMAggregatesReadOK ipam aggregates read o k
*/
type IPAMAggregatesReadOK struct {
}

func (o *IPAMAggregatesReadOK) Error() string {
	return fmt.Sprintf("[GET /api/ipam/aggregates/{id}/][%d] ipamAggregatesReadOK ", 200)
}

func (o *IPAMAggregatesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
