// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// IPAMRolesReadReader is a Reader for the IPAMRolesRead structure.
type IPAMRolesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPAMRolesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIPAMRolesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIPAMRolesReadOK creates a IPAMRolesReadOK with default headers values
func NewIPAMRolesReadOK() *IPAMRolesReadOK {
	return &IPAMRolesReadOK{}
}

/*IPAMRolesReadOK handles this case with default header values.

IPAMRolesReadOK ipam roles read o k
*/
type IPAMRolesReadOK struct {
}

func (o *IPAMRolesReadOK) Error() string {
	return fmt.Sprintf("[GET /api/ipam/roles/{id}/][%d] ipamRolesReadOK ", 200)
}

func (o *IPAMRolesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
