// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// IPAMIPAddressesReadReader is a Reader for the IPAMIPAddressesRead structure.
type IPAMIPAddressesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPAMIPAddressesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIPAMIPAddressesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIPAMIPAddressesReadOK creates a IPAMIPAddressesReadOK with default headers values
func NewIPAMIPAddressesReadOK() *IPAMIPAddressesReadOK {
	return &IPAMIPAddressesReadOK{}
}

/*IPAMIPAddressesReadOK handles this case with default header values.

IPAMIPAddressesReadOK ipam Ip addresses read o k
*/
type IPAMIPAddressesReadOK struct {
}

func (o *IPAMIPAddressesReadOK) Error() string {
	return fmt.Sprintf("[GET /api/ipam/ip-addresses/{id}/][%d] ipamIpAddressesReadOK ", 200)
}

func (o *IPAMIPAddressesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
