// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIPAMVlanGroupsReadParams creates a new IPAMVlanGroupsReadParams object
// with the default values initialized.
func NewIPAMVlanGroupsReadParams() *IPAMVlanGroupsReadParams {
	var ()
	return &IPAMVlanGroupsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIPAMVlanGroupsReadParamsWithTimeout creates a new IPAMVlanGroupsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIPAMVlanGroupsReadParamsWithTimeout(timeout time.Duration) *IPAMVlanGroupsReadParams {
	var ()
	return &IPAMVlanGroupsReadParams{

		timeout: timeout,
	}
}

// NewIPAMVlanGroupsReadParamsWithContext creates a new IPAMVlanGroupsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewIPAMVlanGroupsReadParamsWithContext(ctx context.Context) *IPAMVlanGroupsReadParams {
	var ()
	return &IPAMVlanGroupsReadParams{

		Context: ctx,
	}
}

// NewIPAMVlanGroupsReadParamsWithHTTPClient creates a new IPAMVlanGroupsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIPAMVlanGroupsReadParamsWithHTTPClient(client *http.Client) *IPAMVlanGroupsReadParams {
	var ()
	return &IPAMVlanGroupsReadParams{
		HTTPClient: client,
	}
}

/*IPAMVlanGroupsReadParams contains all the parameters to send to the API endpoint
for the ipam vlan groups read operation typically these are written to a http.Request
*/
type IPAMVlanGroupsReadParams struct {

	/*ID
	  A unique integer value identifying this VLAN group.

	*/
	ID int64
	/*Name*/
	Name *string
	/*Site*/
	Site *string
	/*SiteID*/
	SiteID *string
	/*Slug*/
	Slug *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) WithTimeout(timeout time.Duration) *IPAMVlanGroupsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) WithContext(ctx context.Context) *IPAMVlanGroupsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) WithHTTPClient(client *http.Client) *IPAMVlanGroupsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) WithID(id int64) *IPAMVlanGroupsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) SetID(id int64) {
	o.ID = id
}

// WithName adds the name to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) WithName(name *string) *IPAMVlanGroupsReadParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) SetName(name *string) {
	o.Name = name
}

// WithSite adds the site to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) WithSite(site *string) *IPAMVlanGroupsReadParams {
	o.SetSite(site)
	return o
}

// SetSite adds the site to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) SetSite(site *string) {
	o.Site = site
}

// WithSiteID adds the siteID to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) WithSiteID(siteID *string) *IPAMVlanGroupsReadParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) SetSiteID(siteID *string) {
	o.SiteID = siteID
}

// WithSlug adds the slug to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) WithSlug(slug *string) *IPAMVlanGroupsReadParams {
	o.SetSlug(slug)
	return o
}

// SetSlug adds the slug to the ipam vlan groups read params
func (o *IPAMVlanGroupsReadParams) SetSlug(slug *string) {
	o.Slug = slug
}

// WriteToRequest writes these params to a swagger request
func (o *IPAMVlanGroupsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Site != nil {

		// query param site
		var qrSite string
		if o.Site != nil {
			qrSite = *o.Site
		}
		qSite := qrSite
		if qSite != "" {
			if err := r.SetQueryParam("site", qSite); err != nil {
				return err
			}
		}

	}

	if o.SiteID != nil {

		// query param site_id
		var qrSiteID string
		if o.SiteID != nil {
			qrSiteID = *o.SiteID
		}
		qSiteID := qrSiteID
		if qSiteID != "" {
			if err := r.SetQueryParam("site_id", qSiteID); err != nil {
				return err
			}
		}

	}

	if o.Slug != nil {

		// query param slug
		var qrSlug string
		if o.Slug != nil {
			qrSlug = *o.Slug
		}
		qSlug := qrSlug
		if qSlug != "" {
			if err := r.SetQueryParam("slug", qSlug); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
