// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// IPAMAggregatesListReader is a Reader for the IPAMAggregatesList structure.
type IPAMAggregatesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPAMAggregatesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIPAMAggregatesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIPAMAggregatesListOK creates a IPAMAggregatesListOK with default headers values
func NewIPAMAggregatesListOK() *IPAMAggregatesListOK {
	return &IPAMAggregatesListOK{}
}

/*IPAMAggregatesListOK handles this case with default header values.

IPAMAggregatesListOK ipam aggregates list o k
*/
type IPAMAggregatesListOK struct {
}

func (o *IPAMAggregatesListOK) Error() string {
	return fmt.Sprintf("[GET /api/ipam/aggregates/][%d] ipamAggregatesListOK ", 200)
}

func (o *IPAMAggregatesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
