// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// IPAMVlansListReader is a Reader for the IPAMVlansList structure.
type IPAMVlansListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPAMVlansListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIPAMVlansListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIPAMVlansListOK creates a IPAMVlansListOK with default headers values
func NewIPAMVlansListOK() *IPAMVlansListOK {
	return &IPAMVlansListOK{}
}

/*IPAMVlansListOK handles this case with default header values.

IPAMVlansListOK ipam vlans list o k
*/
type IPAMVlansListOK struct {
}

func (o *IPAMVlansListOK) Error() string {
	return fmt.Sprintf("[GET /api/ipam/vlans/][%d] ipamVlansListOK ", 200)
}

func (o *IPAMVlansListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
