// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDcimConsoleServerPortsReadParams creates a new DcimConsoleServerPortsReadParams object
// with the default values initialized.
func NewDcimConsoleServerPortsReadParams() *DcimConsoleServerPortsReadParams {
	var ()
	return &DcimConsoleServerPortsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDcimConsoleServerPortsReadParamsWithTimeout creates a new DcimConsoleServerPortsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDcimConsoleServerPortsReadParamsWithTimeout(timeout time.Duration) *DcimConsoleServerPortsReadParams {
	var ()
	return &DcimConsoleServerPortsReadParams{

		timeout: timeout,
	}
}

// NewDcimConsoleServerPortsReadParamsWithContext creates a new DcimConsoleServerPortsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewDcimConsoleServerPortsReadParamsWithContext(ctx context.Context) *DcimConsoleServerPortsReadParams {
	var ()
	return &DcimConsoleServerPortsReadParams{

		Context: ctx,
	}
}

// NewDcimConsoleServerPortsReadParamsWithHTTPClient creates a new DcimConsoleServerPortsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDcimConsoleServerPortsReadParamsWithHTTPClient(client *http.Client) *DcimConsoleServerPortsReadParams {
	var ()
	return &DcimConsoleServerPortsReadParams{
		HTTPClient: client,
	}
}

/*DcimConsoleServerPortsReadParams contains all the parameters to send to the API endpoint
for the dcim console server ports read operation typically these are written to a http.Request
*/
type DcimConsoleServerPortsReadParams struct {

	/*Device*/
	Device *string
	/*DeviceID*/
	DeviceID *string
	/*ID
	  A unique integer value identifying this console server port.

	*/
	ID int64
	/*Name*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) WithTimeout(timeout time.Duration) *DcimConsoleServerPortsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) WithContext(ctx context.Context) *DcimConsoleServerPortsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) WithHTTPClient(client *http.Client) *DcimConsoleServerPortsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevice adds the device to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) WithDevice(device *string) *DcimConsoleServerPortsReadParams {
	o.SetDevice(device)
	return o
}

// SetDevice adds the device to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) SetDevice(device *string) {
	o.Device = device
}

// WithDeviceID adds the deviceID to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) WithDeviceID(deviceID *string) *DcimConsoleServerPortsReadParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) SetDeviceID(deviceID *string) {
	o.DeviceID = deviceID
}

// WithID adds the id to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) WithID(id int64) *DcimConsoleServerPortsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) SetID(id int64) {
	o.ID = id
}

// WithName adds the name to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) WithName(name *string) *DcimConsoleServerPortsReadParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the dcim console server ports read params
func (o *DcimConsoleServerPortsReadParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DcimConsoleServerPortsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Device != nil {

		// query param device
		var qrDevice string
		if o.Device != nil {
			qrDevice = *o.Device
		}
		qDevice := qrDevice
		if qDevice != "" {
			if err := r.SetQueryParam("device", qDevice); err != nil {
				return err
			}
		}

	}

	if o.DeviceID != nil {

		// query param device_id
		var qrDeviceID string
		if o.DeviceID != nil {
			qrDeviceID = *o.DeviceID
		}
		qDeviceID := qrDeviceID
		if qDeviceID != "" {
			if err := r.SetQueryParam("device_id", qDeviceID); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
