// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimConsolePortTemplatesReadReader is a Reader for the DcimConsolePortTemplatesRead structure.
type DcimConsolePortTemplatesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimConsolePortTemplatesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimConsolePortTemplatesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimConsolePortTemplatesReadOK creates a DcimConsolePortTemplatesReadOK with default headers values
func NewDcimConsolePortTemplatesReadOK() *DcimConsolePortTemplatesReadOK {
	return &DcimConsolePortTemplatesReadOK{}
}

/*DcimConsolePortTemplatesReadOK handles this case with default header values.

DcimConsolePortTemplatesReadOK dcim console port templates read o k
*/
type DcimConsolePortTemplatesReadOK struct {
}

func (o *DcimConsolePortTemplatesReadOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/console-port-templates/{id}/][%d] dcimConsolePortTemplatesReadOK ", 200)
}

func (o *DcimConsolePortTemplatesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
