// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimPowerOutletsReadReader is a Reader for the DcimPowerOutletsRead structure.
type DcimPowerOutletsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimPowerOutletsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimPowerOutletsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimPowerOutletsReadOK creates a DcimPowerOutletsReadOK with default headers values
func NewDcimPowerOutletsReadOK() *DcimPowerOutletsReadOK {
	return &DcimPowerOutletsReadOK{}
}

/*DcimPowerOutletsReadOK handles this case with default header values.

DcimPowerOutletsReadOK dcim power outlets read o k
*/
type DcimPowerOutletsReadOK struct {
}

func (o *DcimPowerOutletsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/power-outlets/{id}/][%d] dcimPowerOutletsReadOK ", 200)
}

func (o *DcimPowerOutletsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
