// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimConsoleServerPortsListReader is a Reader for the DcimConsoleServerPortsList structure.
type DcimConsoleServerPortsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimConsoleServerPortsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimConsoleServerPortsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimConsoleServerPortsListOK creates a DcimConsoleServerPortsListOK with default headers values
func NewDcimConsoleServerPortsListOK() *DcimConsoleServerPortsListOK {
	return &DcimConsoleServerPortsListOK{}
}

/*DcimConsoleServerPortsListOK handles this case with default header values.

DcimConsoleServerPortsListOK dcim console server ports list o k
*/
type DcimConsoleServerPortsListOK struct {
}

func (o *DcimConsoleServerPortsListOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/console-server-ports/][%d] dcimConsoleServerPortsListOK ", 200)
}

func (o *DcimConsoleServerPortsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
