// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimInterfaceTemplatesReadReader is a Reader for the DcimInterfaceTemplatesRead structure.
type DcimInterfaceTemplatesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimInterfaceTemplatesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimInterfaceTemplatesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimInterfaceTemplatesReadOK creates a DcimInterfaceTemplatesReadOK with default headers values
func NewDcimInterfaceTemplatesReadOK() *DcimInterfaceTemplatesReadOK {
	return &DcimInterfaceTemplatesReadOK{}
}

/*DcimInterfaceTemplatesReadOK handles this case with default header values.

DcimInterfaceTemplatesReadOK dcim interface templates read o k
*/
type DcimInterfaceTemplatesReadOK struct {
}

func (o *DcimInterfaceTemplatesReadOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/interface-templates/{id}/][%d] dcimInterfaceTemplatesReadOK ", 200)
}

func (o *DcimInterfaceTemplatesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
