// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimPowerConnectionsListReader is a Reader for the DcimPowerConnectionsList structure.
type DcimPowerConnectionsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimPowerConnectionsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimPowerConnectionsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimPowerConnectionsListOK creates a DcimPowerConnectionsListOK with default headers values
func NewDcimPowerConnectionsListOK() *DcimPowerConnectionsListOK {
	return &DcimPowerConnectionsListOK{}
}

/*DcimPowerConnectionsListOK handles this case with default header values.

DcimPowerConnectionsListOK dcim power connections list o k
*/
type DcimPowerConnectionsListOK struct {
}

func (o *DcimPowerConnectionsListOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/power-connections/][%d] dcimPowerConnectionsListOK ", 200)
}

func (o *DcimPowerConnectionsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
