// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimDeviceBaysListReader is a Reader for the DcimDeviceBaysList structure.
type DcimDeviceBaysListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimDeviceBaysListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimDeviceBaysListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimDeviceBaysListOK creates a DcimDeviceBaysListOK with default headers values
func NewDcimDeviceBaysListOK() *DcimDeviceBaysListOK {
	return &DcimDeviceBaysListOK{}
}

/*DcimDeviceBaysListOK handles this case with default header values.

DcimDeviceBaysListOK dcim device bays list o k
*/
type DcimDeviceBaysListOK struct {
}

func (o *DcimDeviceBaysListOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/device-bays/][%d] dcimDeviceBaysListOK ", 200)
}

func (o *DcimDeviceBaysListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
