// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimPlatformsReadReader is a Reader for the DcimPlatformsRead structure.
type DcimPlatformsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimPlatformsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimPlatformsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimPlatformsReadOK creates a DcimPlatformsReadOK with default headers values
func NewDcimPlatformsReadOK() *DcimPlatformsReadOK {
	return &DcimPlatformsReadOK{}
}

/*DcimPlatformsReadOK handles this case with default header values.

DcimPlatformsReadOK dcim platforms read o k
*/
type DcimPlatformsReadOK struct {
}

func (o *DcimPlatformsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/platforms/{id}/][%d] dcimPlatformsReadOK ", 200)
}

func (o *DcimPlatformsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
