// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimPlatformsListReader is a Reader for the DcimPlatformsList structure.
type DcimPlatformsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimPlatformsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimPlatformsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimPlatformsListOK creates a DcimPlatformsListOK with default headers values
func NewDcimPlatformsListOK() *DcimPlatformsListOK {
	return &DcimPlatformsListOK{}
}

/*DcimPlatformsListOK handles this case with default header values.

DcimPlatformsListOK dcim platforms list o k
*/
type DcimPlatformsListOK struct {
}

func (o *DcimPlatformsListOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/platforms/][%d] dcimPlatformsListOK ", 200)
}

func (o *DcimPlatformsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
