// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimInterfacesGraphsReader is a Reader for the DcimInterfacesGraphs structure.
type DcimInterfacesGraphsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimInterfacesGraphsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimInterfacesGraphsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimInterfacesGraphsOK creates a DcimInterfacesGraphsOK with default headers values
func NewDcimInterfacesGraphsOK() *DcimInterfacesGraphsOK {
	return &DcimInterfacesGraphsOK{}
}

/*DcimInterfacesGraphsOK handles this case with default header values.

DcimInterfacesGraphsOK dcim interfaces graphs o k
*/
type DcimInterfacesGraphsOK struct {
}

func (o *DcimInterfacesGraphsOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/interfaces/{id}/graphs/][%d] dcimInterfacesGraphsOK ", 200)
}

func (o *DcimInterfacesGraphsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
