// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDcimDeviceRolesReadParams creates a new DcimDeviceRolesReadParams object
// with the default values initialized.
func NewDcimDeviceRolesReadParams() *DcimDeviceRolesReadParams {
	var ()
	return &DcimDeviceRolesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDcimDeviceRolesReadParamsWithTimeout creates a new DcimDeviceRolesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDcimDeviceRolesReadParamsWithTimeout(timeout time.Duration) *DcimDeviceRolesReadParams {
	var ()
	return &DcimDeviceRolesReadParams{

		timeout: timeout,
	}
}

// NewDcimDeviceRolesReadParamsWithContext creates a new DcimDeviceRolesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewDcimDeviceRolesReadParamsWithContext(ctx context.Context) *DcimDeviceRolesReadParams {
	var ()
	return &DcimDeviceRolesReadParams{

		Context: ctx,
	}
}

// NewDcimDeviceRolesReadParamsWithHTTPClient creates a new DcimDeviceRolesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDcimDeviceRolesReadParamsWithHTTPClient(client *http.Client) *DcimDeviceRolesReadParams {
	var ()
	return &DcimDeviceRolesReadParams{
		HTTPClient: client,
	}
}

/*DcimDeviceRolesReadParams contains all the parameters to send to the API endpoint
for the dcim device roles read operation typically these are written to a http.Request
*/
type DcimDeviceRolesReadParams struct {

	/*Color*/
	Color *string
	/*ID
	  A unique integer value identifying this device role.

	*/
	ID int64
	/*Name*/
	Name *string
	/*Slug*/
	Slug *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) WithTimeout(timeout time.Duration) *DcimDeviceRolesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) WithContext(ctx context.Context) *DcimDeviceRolesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) WithHTTPClient(client *http.Client) *DcimDeviceRolesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithColor adds the color to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) WithColor(color *string) *DcimDeviceRolesReadParams {
	o.SetColor(color)
	return o
}

// SetColor adds the color to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) SetColor(color *string) {
	o.Color = color
}

// WithID adds the id to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) WithID(id int64) *DcimDeviceRolesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) SetID(id int64) {
	o.ID = id
}

// WithName adds the name to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) WithName(name *string) *DcimDeviceRolesReadParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) SetName(name *string) {
	o.Name = name
}

// WithSlug adds the slug to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) WithSlug(slug *string) *DcimDeviceRolesReadParams {
	o.SetSlug(slug)
	return o
}

// SetSlug adds the slug to the dcim device roles read params
func (o *DcimDeviceRolesReadParams) SetSlug(slug *string) {
	o.Slug = slug
}

// WriteToRequest writes these params to a swagger request
func (o *DcimDeviceRolesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Color != nil {

		// query param color
		var qrColor string
		if o.Color != nil {
			qrColor = *o.Color
		}
		qColor := qrColor
		if qColor != "" {
			if err := r.SetQueryParam("color", qColor); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Slug != nil {

		// query param slug
		var qrSlug string
		if o.Slug != nil {
			qrSlug = *o.Slug
		}
		qSlug := qrSlug
		if qSlug != "" {
			if err := r.SetQueryParam("slug", qSlug); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
