// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDcimInterfaceTemplatesReadParams creates a new DcimInterfaceTemplatesReadParams object
// with the default values initialized.
func NewDcimInterfaceTemplatesReadParams() *DcimInterfaceTemplatesReadParams {
	var ()
	return &DcimInterfaceTemplatesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDcimInterfaceTemplatesReadParamsWithTimeout creates a new DcimInterfaceTemplatesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDcimInterfaceTemplatesReadParamsWithTimeout(timeout time.Duration) *DcimInterfaceTemplatesReadParams {
	var ()
	return &DcimInterfaceTemplatesReadParams{

		timeout: timeout,
	}
}

// NewDcimInterfaceTemplatesReadParamsWithContext creates a new DcimInterfaceTemplatesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewDcimInterfaceTemplatesReadParamsWithContext(ctx context.Context) *DcimInterfaceTemplatesReadParams {
	var ()
	return &DcimInterfaceTemplatesReadParams{

		Context: ctx,
	}
}

// NewDcimInterfaceTemplatesReadParamsWithHTTPClient creates a new DcimInterfaceTemplatesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDcimInterfaceTemplatesReadParamsWithHTTPClient(client *http.Client) *DcimInterfaceTemplatesReadParams {
	var ()
	return &DcimInterfaceTemplatesReadParams{
		HTTPClient: client,
	}
}

/*DcimInterfaceTemplatesReadParams contains all the parameters to send to the API endpoint
for the dcim interface templates read operation typically these are written to a http.Request
*/
type DcimInterfaceTemplatesReadParams struct {

	/*DevicetypeID*/
	DevicetypeID *string
	/*FormFactor*/
	FormFactor *string
	/*ID
	  A unique integer value identifying this interface template.

	*/
	ID int64
	/*MgmtOnly*/
	MgmtOnly *string
	/*Name*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) WithTimeout(timeout time.Duration) *DcimInterfaceTemplatesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) WithContext(ctx context.Context) *DcimInterfaceTemplatesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) WithHTTPClient(client *http.Client) *DcimInterfaceTemplatesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevicetypeID adds the devicetypeID to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) WithDevicetypeID(devicetypeID *string) *DcimInterfaceTemplatesReadParams {
	o.SetDevicetypeID(devicetypeID)
	return o
}

// SetDevicetypeID adds the devicetypeId to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) SetDevicetypeID(devicetypeID *string) {
	o.DevicetypeID = devicetypeID
}

// WithFormFactor adds the formFactor to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) WithFormFactor(formFactor *string) *DcimInterfaceTemplatesReadParams {
	o.SetFormFactor(formFactor)
	return o
}

// SetFormFactor adds the formFactor to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) SetFormFactor(formFactor *string) {
	o.FormFactor = formFactor
}

// WithID adds the id to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) WithID(id int64) *DcimInterfaceTemplatesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) SetID(id int64) {
	o.ID = id
}

// WithMgmtOnly adds the mgmtOnly to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) WithMgmtOnly(mgmtOnly *string) *DcimInterfaceTemplatesReadParams {
	o.SetMgmtOnly(mgmtOnly)
	return o
}

// SetMgmtOnly adds the mgmtOnly to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) SetMgmtOnly(mgmtOnly *string) {
	o.MgmtOnly = mgmtOnly
}

// WithName adds the name to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) WithName(name *string) *DcimInterfaceTemplatesReadParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the dcim interface templates read params
func (o *DcimInterfaceTemplatesReadParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DcimInterfaceTemplatesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DevicetypeID != nil {

		// query param devicetype_id
		var qrDevicetypeID string
		if o.DevicetypeID != nil {
			qrDevicetypeID = *o.DevicetypeID
		}
		qDevicetypeID := qrDevicetypeID
		if qDevicetypeID != "" {
			if err := r.SetQueryParam("devicetype_id", qDevicetypeID); err != nil {
				return err
			}
		}

	}

	if o.FormFactor != nil {

		// query param form_factor
		var qrFormFactor string
		if o.FormFactor != nil {
			qrFormFactor = *o.FormFactor
		}
		qFormFactor := qrFormFactor
		if qFormFactor != "" {
			if err := r.SetQueryParam("form_factor", qFormFactor); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.MgmtOnly != nil {

		// query param mgmt_only
		var qrMgmtOnly string
		if o.MgmtOnly != nil {
			qrMgmtOnly = *o.MgmtOnly
		}
		qMgmtOnly := qrMgmtOnly
		if qMgmtOnly != "" {
			if err := r.SetQueryParam("mgmt_only", qMgmtOnly); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
