// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDcimPowerOutletsReadParams creates a new DcimPowerOutletsReadParams object
// with the default values initialized.
func NewDcimPowerOutletsReadParams() *DcimPowerOutletsReadParams {
	var ()
	return &DcimPowerOutletsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDcimPowerOutletsReadParamsWithTimeout creates a new DcimPowerOutletsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDcimPowerOutletsReadParamsWithTimeout(timeout time.Duration) *DcimPowerOutletsReadParams {
	var ()
	return &DcimPowerOutletsReadParams{

		timeout: timeout,
	}
}

// NewDcimPowerOutletsReadParamsWithContext creates a new DcimPowerOutletsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewDcimPowerOutletsReadParamsWithContext(ctx context.Context) *DcimPowerOutletsReadParams {
	var ()
	return &DcimPowerOutletsReadParams{

		Context: ctx,
	}
}

// NewDcimPowerOutletsReadParamsWithHTTPClient creates a new DcimPowerOutletsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDcimPowerOutletsReadParamsWithHTTPClient(client *http.Client) *DcimPowerOutletsReadParams {
	var ()
	return &DcimPowerOutletsReadParams{
		HTTPClient: client,
	}
}

/*DcimPowerOutletsReadParams contains all the parameters to send to the API endpoint
for the dcim power outlets read operation typically these are written to a http.Request
*/
type DcimPowerOutletsReadParams struct {

	/*Device*/
	Device *string
	/*DeviceID*/
	DeviceID *string
	/*ID
	  A unique integer value identifying this power outlet.

	*/
	ID int64
	/*Name*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) WithTimeout(timeout time.Duration) *DcimPowerOutletsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) WithContext(ctx context.Context) *DcimPowerOutletsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) WithHTTPClient(client *http.Client) *DcimPowerOutletsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevice adds the device to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) WithDevice(device *string) *DcimPowerOutletsReadParams {
	o.SetDevice(device)
	return o
}

// SetDevice adds the device to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) SetDevice(device *string) {
	o.Device = device
}

// WithDeviceID adds the deviceID to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) WithDeviceID(deviceID *string) *DcimPowerOutletsReadParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) SetDeviceID(deviceID *string) {
	o.DeviceID = deviceID
}

// WithID adds the id to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) WithID(id int64) *DcimPowerOutletsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) SetID(id int64) {
	o.ID = id
}

// WithName adds the name to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) WithName(name *string) *DcimPowerOutletsReadParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the dcim power outlets read params
func (o *DcimPowerOutletsReadParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DcimPowerOutletsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Device != nil {

		// query param device
		var qrDevice string
		if o.Device != nil {
			qrDevice = *o.Device
		}
		qDevice := qrDevice
		if qDevice != "" {
			if err := r.SetQueryParam("device", qDevice); err != nil {
				return err
			}
		}

	}

	if o.DeviceID != nil {

		// query param device_id
		var qrDeviceID string
		if o.DeviceID != nil {
			qrDeviceID = *o.DeviceID
		}
		qDeviceID := qrDeviceID
		if qDeviceID != "" {
			if err := r.SetQueryParam("device_id", qDeviceID); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
