// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimDeviceRolesReadReader is a Reader for the DcimDeviceRolesRead structure.
type DcimDeviceRolesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimDeviceRolesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimDeviceRolesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimDeviceRolesReadOK creates a DcimDeviceRolesReadOK with default headers values
func NewDcimDeviceRolesReadOK() *DcimDeviceRolesReadOK {
	return &DcimDeviceRolesReadOK{}
}

/*DcimDeviceRolesReadOK handles this case with default header values.

DcimDeviceRolesReadOK dcim device roles read o k
*/
type DcimDeviceRolesReadOK struct {
}

func (o *DcimDeviceRolesReadOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/device-roles/{id}/][%d] dcimDeviceRolesReadOK ", 200)
}

func (o *DcimDeviceRolesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
