// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimSitesGraphsReader is a Reader for the DcimSitesGraphs structure.
type DcimSitesGraphsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimSitesGraphsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimSitesGraphsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimSitesGraphsOK creates a DcimSitesGraphsOK with default headers values
func NewDcimSitesGraphsOK() *DcimSitesGraphsOK {
	return &DcimSitesGraphsOK{}
}

/*DcimSitesGraphsOK handles this case with default header values.

DcimSitesGraphsOK dcim sites graphs o k
*/
type DcimSitesGraphsOK struct {
}

func (o *DcimSitesGraphsOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/sites/{id}/graphs/][%d] dcimSitesGraphsOK ", 200)
}

func (o *DcimSitesGraphsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
