// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DcimPowerPortsListReader is a Reader for the DcimPowerPortsList structure.
type DcimPowerPortsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimPowerPortsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimPowerPortsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimPowerPortsListOK creates a DcimPowerPortsListOK with default headers values
func NewDcimPowerPortsListOK() *DcimPowerPortsListOK {
	return &DcimPowerPortsListOK{}
}

/*DcimPowerPortsListOK handles this case with default header values.

DcimPowerPortsListOK dcim power ports list o k
*/
type DcimPowerPortsListOK struct {
}

func (o *DcimPowerPortsListOK) Error() string {
	return fmt.Sprintf("[GET /api/dcim/power-ports/][%d] dcimPowerPortsListOK ", 200)
}

func (o *DcimPowerPortsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
