// Code generated by go-swagger; DO NOT EDIT.

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ExtrasTopologyMapsListReader is a Reader for the ExtrasTopologyMapsList structure.
type ExtrasTopologyMapsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasTopologyMapsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExtrasTopologyMapsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewExtrasTopologyMapsListOK creates a ExtrasTopologyMapsListOK with default headers values
func NewExtrasTopologyMapsListOK() *ExtrasTopologyMapsListOK {
	return &ExtrasTopologyMapsListOK{}
}

/*ExtrasTopologyMapsListOK handles this case with default header values.

ExtrasTopologyMapsListOK extras topology maps list o k
*/
type ExtrasTopologyMapsListOK struct {
}

func (o *ExtrasTopologyMapsListOK) Error() string {
	return fmt.Sprintf("[GET /api/extras/topology-maps/][%d] extrasTopologyMapsListOK ", 200)
}

func (o *ExtrasTopologyMapsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
