// Code generated by go-swagger; DO NOT EDIT.

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ExtrasImageAttachmentsListReader is a Reader for the ExtrasImageAttachmentsList structure.
type ExtrasImageAttachmentsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasImageAttachmentsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExtrasImageAttachmentsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewExtrasImageAttachmentsListOK creates a ExtrasImageAttachmentsListOK with default headers values
func NewExtrasImageAttachmentsListOK() *ExtrasImageAttachmentsListOK {
	return &ExtrasImageAttachmentsListOK{}
}

/*ExtrasImageAttachmentsListOK handles this case with default header values.

ExtrasImageAttachmentsListOK extras image attachments list o k
*/
type ExtrasImageAttachmentsListOK struct {
}

func (o *ExtrasImageAttachmentsListOK) Error() string {
	return fmt.Sprintf("[GET /api/extras/image-attachments/][%d] extrasImageAttachmentsListOK ", 200)
}

func (o *ExtrasImageAttachmentsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
