// Code generated by go-swagger; DO NOT EDIT.

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ExtrasImageAttachmentsReadReader is a Reader for the ExtrasImageAttachmentsRead structure.
type ExtrasImageAttachmentsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasImageAttachmentsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExtrasImageAttachmentsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewExtrasImageAttachmentsReadOK creates a ExtrasImageAttachmentsReadOK with default headers values
func NewExtrasImageAttachmentsReadOK() *ExtrasImageAttachmentsReadOK {
	return &ExtrasImageAttachmentsReadOK{}
}

/*ExtrasImageAttachmentsReadOK handles this case with default header values.

ExtrasImageAttachmentsReadOK extras image attachments read o k
*/
type ExtrasImageAttachmentsReadOK struct {
}

func (o *ExtrasImageAttachmentsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/extras/image-attachments/{id}/][%d] extrasImageAttachmentsReadOK ", 200)
}

func (o *ExtrasImageAttachmentsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
