// Code generated by go-swagger; DO NOT EDIT.

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ExtrasTopologyMapsReadReader is a Reader for the ExtrasTopologyMapsRead structure.
type ExtrasTopologyMapsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasTopologyMapsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExtrasTopologyMapsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewExtrasTopologyMapsReadOK creates a ExtrasTopologyMapsReadOK with default headers values
func NewExtrasTopologyMapsReadOK() *ExtrasTopologyMapsReadOK {
	return &ExtrasTopologyMapsReadOK{}
}

/*ExtrasTopologyMapsReadOK handles this case with default header values.

ExtrasTopologyMapsReadOK extras topology maps read o k
*/
type ExtrasTopologyMapsReadOK struct {
}

func (o *ExtrasTopologyMapsReadOK) Error() string {
	return fmt.Sprintf("[GET /api/extras/topology-maps/{id}/][%d] extrasTopologyMapsReadOK ", 200)
}

func (o *ExtrasTopologyMapsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
